### ISSUE TITLE
Autotests, extend main_tests.json

### ISSUE THREAD

**Issue by Barashkov-GO** [bmstu-iu9/SCP-Autotests#2]
Дополнить main_tests.json
Можно попробовать таким кодом (и перенаправлением вывода в json файл), если разобраться с кодировкой. Код работает.

![image](https://user-images.githubusercontent.com/67962725/126375769-5e554fe5-6d5a-40b2-9deb-9b9c1014ad95.png)
----------------------------------------------
```
package main

import (
	"errors"
	"fmt"
	"io/ioutil"
	"strings"
)

func main(){
	var path string
	var s string
	var ss []string
	path = "../SCP-Autotests/tests/test_ABmoved.ref"
	fmt.Scan(path)
	data, err := ioutil.ReadFile(path)
	if err != nil {
		errors.New("test not opened")
	}
	s = string(data)
	indBeg := strings.Index(s, "Тесты:")
	indEnd1 := strings.Index(string(data[indBeg:]), "*/")
	indEnd2 := strings.Index(string(data[indBeg:]), "---")
	var indEnd int
	if indEnd1 > indEnd2 {
		indEnd = indEnd2 + indBeg
	} else {
		indEnd = indEnd1 + indBeg
	}
	s = string(data[indBeg + 11:indEnd])
	strings.ReplaceAll(s, " ", "")
	ss = strings.Split(s, ",")
	for _, item := range ss {
		fmt.Printf("\t{\n\t\t\"FilePath\": [\"%s\"],\n\t\t\"TestData\": [\"%s\"]\n\t},\n", strings.ReplaceAll(path, "../SCP-Autotests/", ""), strings.ReplaceAll(item, " ", ""))
	}
}
```

**Comment by TonitaN** [comment]
Сейчас `go test` выдает кучу фейлов на блоке `get_unparameterized_entry_point_tests`, потому что вместо просто вызовов с константными аргументами получаются эти вызовы, обернутые в `Prout`.

**Comment by TonitaN** [comment]
Сейчас `go test` выдает кучу фейлов на блоке `get_unparameterized_entry_point_tests`, потому что вместо просто вызовов с константными аргументами получаются эти вызовы, обернутые в `Prout`.
