### ISSUE TITLE
Испытания на трёх версиях MSCP-A

### ISSUE THREAD

**Issue by TonitaN** [bmstu-iu9/SCP-Autotests#3]
Набор автотестов уже есть, осталось испытать их на трёх версиях MSCP-A. Переслано три разные версии:
* старая, за 2017 год, скорее всего, будет глючить на всём чём возможно;
* тоже старая, за 2019 год, но тесты уже должна проходить;
* версия за начало 2020 года, тоже должна проходить все тесты, причём остаточные программы могут отличаться по форме от тех, которые порождает версия 2019 года, но должны возвращать те же значения на ключевых тестах.

Как поведет себя на тестах версия 2017 года, неизвестно. Скорее всего, будут и баги, и вылет суперкомпилятора, и его зависание. Последнее можно определять по таймауту, но вообще время суперкомпиляции может быть очень большим и без всяких зависаний, поэтому таймаут лучше устанавливать гибкий, по ключу. По умолчанию лучше установить побольше, например, 15 минут. 
Идеально --- установить таймаут в зависимости от работы эталона (здесь --- версия 2020 года). Допустимый предел превышения можно установить так. Если превышает время работы эталона больше, чем на 20%, для тестов, которые работают больше 5 минут, либо больше чем на 50% для тестов, которые считаются больше минуты, но меньше пяти, и больше , чем на 100%+2 секунды для тестов, которые считаются меньше минуты --- выдавать сообщение о таймауте.

**Comment by Mazdaywik** [comment]
Все три версии есть в трёх коммитах в репозитории https://github.com/TonitaN/MSCP-A

**Comment by TonitaN** [comment]
@Mazdaywik, я выслала сборки явно, добавив в каждую соответствующий используемым в ней модулям файл `msсp-a.ref`, собираемый в исполняемый модуль с помощью `rlc`. Две последние совпадают с коммитами, а первая (за 2017) старше первого коммита и немного младше, чем второй.

**Comment by Mazdaywik** [comment]
Все три коммита я делал по тем версиям, которые лежали на сайте. Т.е., получается, первая сборка на сайте была какой-то недоделанной?

`mscp-a.ref` с ссылками `*$FROM` нужен не дял `rlc`, а для `rlmake`, если быть точным.

**Comment by TonitaN** [comment]
Нет, это 2017-го года скорее недоделанная, по сравнению с 2018-го. Нарочно, чтобы глючила побольше :)
